#!/usr/bin/node
// prints a square with first arg as size

if (isNaN(process.argv[2])) {
  console.log('Missing size');
} else {
  for (i = 0; i < parseInt(process.argv[2]); i++) {
    for (j = 0; j < parseInt(process.argv[2]); j++)) {
      console.log('X');
    }
    console.log('\n');
  }
}
